- components/elements/spinner.tsx
- components/profile/dataInfo.tsx
- components/profile/userwrapper.tsx
- pages/about.tsx
- pages/profile/details.tsx
- studio/deskStructure.ts
- studio/schemas/profile.ts
- studio/schemas/schema.ts
- styles/Spinner.module.css
Adds sanity data to profile page and adds a small loading spinner
> #26 setup profile page

- components/lists/donationList/donationDetails.tsx
- components/lists/donationList/donationList.tsx
- components/lists/genericList.tsx
- components/lists/genericListRow.tsx
- components/profile/donations/donationsDistributionGraph.tsx
- components/profile/donations/donationsDistributionTable.tsx
- hooks/useApi.ts
- models.ts
- package-lock.json
- package.json
- pages/profile/index.tsx
- styles/DonationsDetails.module.css
- styles/DonationsDistributionGraph.module.css
- styles/Lists.module.css
Depends on branch [#77-Update-distribution-endpoint](https://github.com/stiftelsen-effekt/effekt-backend/tree/%2377-Update-distribution-endpoint) in backend
> Adds distributions to donation list

- models.ts
- pages/profile/index.tsx
Every year from registered year to this year is showing in list
> #80 all years selector

- components/elements/datepicker.tsx
- components/elements/datepickerinput.tsx
- hooks/useClickOutsideAlerter.ts
- stories/controls/DatePicker.stories.tsx
- stories/controls/DatePickerInput.stories.module.css
- stories/controls/DatePickerInput.stories.tsx
- styles/Elements.module.css
> Adds a basic datepicker component

- stories/lists/AgreementList.stories.tsx
- styles/Donations.module.css
Fixed mobileview for large donationamount so that it gets smaller on small screen and aligned all text to the right.
> #103 fix mobileview large donationamount

- components/stepwize/step.tsx
- components/stepwize/stepwize-container.tsx
- components/stepwize/stepwize.tsx
- package-lock.json
- pages/index.tsx
- styles/Stepwize.module.css
Simple dumb component and component container.
Might be more fruitful to make a empty container,? 
Will need a CSS job.
> Adding stepwize component

- components/lists/agreementList/_queries.ts
- components/lists/agreementList/agreementDetails.tsx
Adds the connection to the cancel agreement button, closes #130
> #130 end agreement

- components/lists/donationList/donationDetails.tsx
- components/main/navbar.tsx
- components/profile/donations/donationsDistributionTable.tsx
- components/profile/navbar.tsx
- styles/Elements.module.css
- styles/Navbar.module.css
> Adds minor fixes to css for colors

- components/sectionContainer.tsx
- styles/Home.module.css
- styles/Layout.module.css
- styles/Navbar.module.css
- styles/SectionContainer.module.css
- styles/Stepwize.module.css
Layout component, Hero section (in Home), SectionContainer updated.
> Fixes on layout component

- components/testimonial.tsx
- package-lock.json
- package.json
- pages/index.tsx
- studio/config/.checksums
- studio/config/@sanity/vision.json
- studio/deskStructure.ts
- studio/schemas/frontpage.ts
- studio/schemas/key-point.ts
- studio/schemas/schema.ts
- studio/schemas/testimonial.ts
- styles/Testemonial.module.css
#163 Create data schemas for frontpage in sanity
WIP - not finished
> feature: add frontpage sanity schema and start implementation

- components/elements/pageheader.tsx
- components/elements/responsiveimage.tsx
- components/elements/teaser.tsx
- components/testimonial.tsx
- package-lock.json
- package.json
- pages/index.tsx
- pages/organizations.tsx
- studio/schemas/link.ts
- studio/schemas/organization.ts
- studio/schemas/schema.ts
- styles/Elements.module.css
- styles/Organizations.module.css
- styles/SectionContainer.module.css
- styles/Testemonial.module.css
- styles/globals.css
Updates organizations page to be in accordance with design
> #179 organizations page

- components/elements/cookiebanner.tsx
- components/main/navbar.tsx
- styles/CookieBanner.module.css
- styles/Navbar.module.css
> Adds basic cookie banner

- components/elements/pageheader.tsx
- pages/[slug].tsx
- studio/schemas/types/pageheader.ts
- styles/PageHeader.module.css
> Adds alternative centered page header

- components/elements/articlepreview.tsx
- components/elements/relatedarticles.tsx
- pages/articles.tsx
- studio/deskStructure.ts
- studio/schemas/pages/articles.ts
- studio/schemas/schema.ts
- styles/ArticlePreview.module.css
- styles/Articles.module.css
- styles/Navbar.module.css
- styles/PageHeader.module.css
> Adds simple articles overview page

- .env.production
- additional.d.ts
- components/main/blocks/BlockContentRenderer.tsx
- pages/[slug].tsx
- pages/_app.tsx
- pages/about.tsx
- pages/api/exit-preview.ts
- pages/api/preview.ts
- pages/articles.tsx
- pages/articles/[slug].tsx
- pages/index.tsx
- pages/organizations.tsx
- pages/profile/agreements.tsx
- pages/profile/details.tsx
- pages/profile/index.tsx
- pages/support.tsx
- studio/deskStructure.ts
- studio/package-lock.json
- studio/package.json
- studio/resolveProductionUrl.ts
- studio/sanity.json
- studio/yarn.lock
- tsconfig.json
Adds previews for generic pages and article pages directly into sanity studio. Removes the need to wait for a build to finish to view changes on a specific page 👀 
Ability to use either
- A preview tab (with option to view in mobile mode)
- Side by side preview tab and editor (with option to view in mobile mode)
- Open preview in separate tab / window
Generic pages and articles have been prioritised for previews, might add the "custom pages" later, or convert custom pages to generic pages system.
Closes #286
> #286 sanity preview

- components/main/blocks/ImpactWidget/ImpactWidget.tsx
> Fixes 47 bug in ImpactWidget

- components/main/widget/components/panes/DonationPane/DonationPane.tsx
- components/main/widget/components/panes/DonorPane/DonorPane.tsx
> Replaces EffektButton with NextButton

- components/shared/components/RadioButton/RadioButtons.module.scss
> Removes blue dot for radio buttons

- studio/components/columnsPreview.jsx
- studio/components/contentSectionPreview.jsx
- studio/components/fullImagePreview.jsx
- studio/components/fullVideoPreview.jsx
- studio/components/htmlEmbedPreview.jsx
- studio/components/normalImagePreview.jsx
- studio/components/paragraphPreview.jsx
- studio/components/pointlistPeview.jsx
- studio/components/questionAndAnswerGroupPreview.jsx
- studio/components/testimonialsPreview.jsx
- studio/schemas/types/columns.ts
- studio/schemas/types/contentsection.ts
- studio/schemas/types/introsection.ts
- studio/schemas/types/pageheader.ts
- studio/schemas/types/questionandanswergroup.ts
- studio/schemas/types/splitview.ts
- studio/schemas/types/testimonials.ts
> Adds preview component for all components used

- next.config.js
> Adds missing redirects

- components/shared/layout/Header/Header.module.scss
- components/shared/layout/Header/Header.tsx
Also fixes unnecessary shrinking of the NavBar when cookies have been accepted. Check it out!
> Fixes NavBar dropdown menus and shrinking

- components/main/blocks/ImpactWidget/ImpactWidget.module.scss
- components/main/blocks/ImpactWidget/ImpactWidget.tsx
- pages/[slug].tsx
- pages/about.tsx
- pages/api/preview.ts
- pages/articles.tsx
- pages/articles/[slug].tsx
- pages/index.tsx
- pages/organizations.tsx
- pages/support.tsx
- studio/deskStructure.ts
- studio/package-lock.json
- studio/yarn.lock
> #373 custom page preview

- components/main/blocks/BlockContentRenderer.tsx
- components/main/blocks/Quote/Quote.module.scss
- components/main/blocks/Quote/Quote.tsx
- components/main/blocks/Testemonial/Testemonial.module.scss
- pages/[slug].tsx
- studio/schemas/schema.ts
- studio/schemas/types/contentsection.ts
- studio/schemas/types/quote.ts
> Adds a quote component and fixes a sizing bug

- components/profile/details/ProfileInfo/ProfileInfo.tsx
> Fixes crash for donors with no name on profile page

- pages/profile/agreements.tsx
> Restrict pending agreement counting to agreements created the last week

- components/main/blocks/Paragraph/Paragraph.module.scss
> Increases spacing in ordered and unordered lists in paragraphs

- components/profile/layout/userwrapper.tsx
- pages/api/preview.ts
- pages/vippsagreement.tsx
- studio/deskStructure.ts
- studio/schemas/pages/vippsagreement.ts
- studio/schemas/schema.ts
Creates a new page describing the process for changing vipps agreements
> Adds vipps agreement login page

- components/shared/components/Widget/components/panes/DonationPane/ShareSelection.tsx
- cypress/e2e/widget.js
> Adds restiction on shared selection input fields and adds test

- pages/profile/agreements.tsx
> Fixes typo in pending agreement notification

- components/main/layout/navbar.tsx
- components/profile/layout/navbar.tsx
- components/shared/layout/Navbar/Navbar.module.scss
> Fixes button placement and hamburger menu color

- components/main/blocks/Testemonial/Testemonial.module.scss
- components/main/blocks/Testemonial/Testemonial.tsx
- studio/schemas/types/testimonial.ts
> Adds rich text to testimonal background

- components/profile/layout/layout.tsx
- components/profile/tax/FacebookTab/FacebookTab.module.scss
- components/profile/tax/FacebookTab/FacebookTab.tsx
- components/profile/tax/TaxDeductionsTab/TaxDeductionsTab.module.scss
- components/profile/tax/TaxDeductionsTab/TaxDeductionsTab.tsx
- components/profile/tax/TaxMenu/TaxMenu.module.scss
- components/profile/tax/TaxMenu/TaxMenu.tsx
- components/profile/tax/TaxUnitsTab/TaxUnitsTab.module.scss
- components/profile/tax/TaxUnitsTab/TaxUnitsTab.tsx
- pages/profile/tax.tsx
- studio/deskStructure.ts
- studio/schemas/pages/profile.ts
- studio/schemas/pages/tax.ts
- studio/schemas/schema.ts
- styles/Tax.module.css
@EliseAndresen I've created a branch which I intend to use for all PR's related to tax units, and then we'll merge that branch into main when the time comes :)
> Adds tax unit tabs

- components/profile/donations/DonationImpact/DonationImpactItem.module.scss
> Aligns impact estimate details text to the left for better legibility

- components/shared/components/Widget/components/panes/DonorPane/DonorPane.tsx
> Set autocomplete to "off" for donation widget

- studio/schemas/types/citation.ts
> Updates note preview

- components/main/layout/RelatedArticles/ArticlePreview.module.scss
- pages/articles.tsx
Adds body content to article preview if no ingress is present
> Fallback for article previews to body content

- components/profile/tax/FacebookTab/FacebookTab.tsx
- components/profile/tax/FacebookTaxWidget/FacebookTaxWidget.tsx
- components/profile/tax/TaxMenu/TaxMenu.tsx
> Updates Facbook donation form and text to include Instagram

- components/main/blocks/Testemonial/Testemonial.module.scss
- components/main/blocks/Testemonial/Testemonial.tsx
> #550 testimonial dots

- components/shared/layout/Navbar/Navbar.module.scss
Spacing in the menu is not uniform, artikler is too close to min side button
#582 
---
Tests  
⏲️ Time spent on CR: 2 min
⏲️ Time spent on QA: 2 min
> Adds padding to nav btn group to get spacing that matches menu items

- components/profile/shared/lists/GenericList.tsx
- components/profile/shared/lists/GenericListRow.tsx
- components/profile/shared/lists/taxYearlyReportsList/TaxYearlyReportList.tsx
- components/profile/shared/lists/taxYearlyReportsList/TaxYearlyReportListBody.tsx
- components/profile/shared/lists/taxYearlyReportsList/TaxYearlyReportListSupplemental.tsx
- components/profile/tax/YearlyReportsTab/YearlyReportsTab.tsx
- components/shared/components/Infobox/Infobox.tsx
- components/shared/components/Lightbox/Lightbox.tsx
- cypress/e2e/donations.js
- cypress/e2e/yearly-reports-crypto-donations.js
- cypress/e2e/yearly-reports-ea-funds-donations.js
- cypress/e2e/yearly-reports-missing-ssn.js
- cypress/e2e/yearly-reports-no-data.js
- cypress/e2e/yearly-reports-valid.js
- cypress/fixtures/tax-reports/crypto.json
- cypress/fixtures/tax-reports/ea-funds.json
- cypress/fixtures/tax-reports/empty.json
- cypress/fixtures/tax-reports/missing-ssn.json
- cypress/fixtures/tax-reports/valid.json
Adds e2e tests for yearly reports
#598 
---
Tests  
> 598 e2e tests for yearly reports

- components/main/blocks/BlockContentRenderer.tsx
- components/main/blocks/NewsletterSignup/NewsletterSignup.module.scss
- components/main/blocks/NewsletterSignup/NewsletterSignup.tsx
- components/shared/layout/Footer/Footer.module.scss
- components/shared/layout/Footer/Footer.tsx
- studio/schemas/schema.ts
- studio/schemas/types/contentsection.ts
- studio/schemas/types/newslettersignup.ts
Adds a newsletter signup block
#685
---
Tests  
> Adds newsletter signup as a block

- _queries.ts
- pages/artikler.tsx
- pages/ofte-stilte-sporsmal.tsx
- pages/om.tsx
- pages/topplista.tsx
- pages/vippsavtale.tsx
- studio/schemas/types/questionandanswer.ts
Adds nav item as an option to Q and A links
#275 
---
Tests  
> Adds navitem to Q and A answers and refactors link queries

- .github/workflows/ci.yml
Only run cypress for main-site environment by checking if the deployed target_url contains main-site
---
Tests  
> Only run cypress for main-site environment

- .prettierignore
- studio/.eslintrc
- studio/components/citationRenderer.jsx
- studio/components/columnsPreview.jsx
- studio/components/contactPreview.jsx
- studio/components/contentSectionPreview.jsx
- studio/components/fullImagePreview.jsx
- studio/components/fullVideoPreview.jsx
- studio/components/htmlEmbedPreview.jsx
- studio/components/linksPreview.jsx
- studio/components/normalImagePreview.jsx
- studio/components/paragraphPreview.jsx
- studio/components/pointlistPeview.jsx
- studio/components/questionAndAnswerGroupPreview.jsx
- studio/components/sectionPreview.jsx
- studio/components/testimonialsPreview.jsx
- studio/deskStructure.ts
- studio/package-lock.json
- studio/package.json
- studio/resolveProductionUrl.ts
- studio/tsconfig.json
Seems like files in studio were ignored by prettier, perhaps we should include them too?
---
Tests
> Prettier studio

- .github/workflows/ci.yml
Seems like we are slightly constrained by the e2e test performance on our ci pipeline, this might speed it up?
---
Tests
> Adds paralell e2e testing

- components/main/blocks/WealthCalculator/WealthCalculator.tsx
- components/shared/components/EffektDropdown/EffektDropdown.tsx
- components/shared/components/EffektSlider/EffektSlider.tsx
- cypress/e2e/wealthcalculator.js
Adds basic tests for the wealth calculator
- closes #650 
---
Tests
> Adds cypress tests to wealth calculator

- _queries.ts
- components/main/blocks/BlockContentRenderer.tsx
- components/main/blocks/SplitView/SplitView.module.scss
- components/main/blocks/SplitView/SplitView.tsx
- pages/index.tsx
- studio/schemas/pages/frontpage.ts
- studio/schemas/types/splitview.ts
And adds malariaday to frontpage
Turns out we already had basically the component we needed. I massaged it to meet our requrements.
- closes #649 
---
Tests
> Updates splitview to conform to new teaser requirements

- README.md
- package.json
- studio/package.json
- studio/scripts/listPages.js
It would also be really useful to quickly lookup page document ids, adds a basic command for this
---
Tests
> List pages command

- _queries.ts
- components/main/blocks/BlockContentRenderer.tsx
- components/main/blocks/OrganizationsList/OrganizationsList.module.scss
- components/main/blocks/OrganizationsList/OrganizationsList.tsx
- studio/components/organizationsListPreview.jsx
- studio/schemas/schema.ts
- studio/schemas/types/contentsection.ts
- studio/schemas/types/organizationslist.ts
Add generic organizations list
- closes #670
---
Tests
> #670 generic organizations list

- components/main/blocks/BlockContentRenderer.tsx
- components/main/blocks/GiveBlock/GiveBlock.module.scss
- components/main/blocks/GiveBlock/GiveBlock.tsx
- pages/om.tsx
- studio/schemas/schema.ts
- studio/schemas/types/contentsection.ts
- studio/schemas/types/giveblock.ts
Adds generic give block
- closes #625
---
Tests
> #625 generic give block

- _queries.ts
- components/main/blocks/BlockContentRenderer.tsx
- studio/schemas/types/contentsection.ts
Adds generic wealth calculator teaser to content section
- closes #632
---
Tests
> Generic wealth calculator teaser

- components/main/blocks/BlockContentRenderer.tsx
- components/main/layout/SectionContainer/SectionContainer.module.scss
- components/main/layout/SectionContainer/sectionContainer.tsx
- studio/schemas/types/contentsection.ts
- Adds fieldset for section layout options
- Adds a `ypadded` layout option
---
Tests
> Vertical section padding

- pages/GenericPage.tsx
- pages/[[...slug]].page.tsx
- pages/_app.page.tsx
Had to reopen since #704 was set to faulty base
---
Tests
> Nested generic paths

- components/main/blocks/Links/Links.tsx
- components/main/blocks/WealthCalculatorTeaser/WealthCalculatorTeaser.tsx
- components/main/layout/RelatedArticles/ArticlePreview.tsx
- components/main/layout/RelatedArticles/RelatedArticles.tsx
- context/RouterContext.ts
- pages/ArticlePage.tsx
- pages/ArticlesPage.tsx
- pages/VippsAgreementPage.tsx
- pages/[[...slug]].page.tsx
- pages/min-side/avtaler.page.tsx
- pages/sitemap.xml.page.tsx
- studio/deskStructure.ts
- studio/schemas/schema.ts
- studio/schemas/siteSettings.ts
- studio/schemas/types/paymentproviders/vipps.ts
In cms settings, add vipps payment provider and configure the vippsavtale page from there.
- closes #691
---
Tests
> #691 generic vippsavtale page

- components/profile/layout/layout.tsx
No need as we're attaching all required permissions to the role
```json
{
"https://gieffektivt.no/user-id": 27,
"https://gieffektivt.no/roles": [
"donor"
],
"iss": "https://gieffektivt.eu.auth0.com/",
"sub": "auth0|63ff5798be60c526f4d3ac3a",
"aud": [
"https://data.gieffektivt.no",
"https://gieffektivt.eu.auth0.com/userinfo"
],
"iat": 1683626143,
"exp": 1683712543,
"azp": "y70pumEKFogcX8wK28Fhmun0tlPx6q7B",
"scope": "openid profile email",
"permissions": [
"read:agreements",
"read:distributions",
"read:donations",
"read:profile",
"write:agreements",
"write:distributions",
"write:profile"
]
}
```
---
Tests
> Skip scope requests

- components/profile/_queries.ts
- components/profile/details/ProfileInfo/ProfileInfo.tsx
- components/profile/layout/MissingNameModal/MissingNameModal.module.scss
- components/profile/layout/MissingNameModal/MissingNameModal.tsx
- components/profile/layout/layout.tsx
- components/profile/shared/TaxUnitModal/TaxUnitCreateModal.tsx
- components/profile/shared/TaxUnitModal/TaxUnitModal.module.scss
- components/shared/components/EffektTextInput/EffektTextInput.module.scss
- components/shared/components/EffektTextInput/EffektTextInput.tsx
Adds a modal for when users are missing a name, which notifies them and asks them to add it.
- closes #717 
---
Tests
> Adds a missing name modal

- _queries.ts
Fixes broken links on om oss page
- closes #721 
---
Tests
> Fixes about us links

- components/main/blocks/WealthCalculatorTeaser/WealthCalculatorTeaser.tsx
Logaritmisk was spelled wrong :P 
- closes #726 
---
Tests
> Fixed typo

- components/profile/vipps/AnonymousVippsAgreement.module.scss
Just a small visual fix for the mobile view of Vipps anonymous agreements.
---
Tests
> Fixes styling bug for Vipps anon mobile view

- components/profile/shared/lists/taxYearlyReportsList/TaxYearlyReportList.tsx
- components/profile/shared/lists/taxYearlyReportsList/TaxYearlyReportMobileList.tsx
- components/profile/tax/YearlyReportsTab/YearlyReportsTab.tsx
Removes text no lenger relevant for 2022.
---
Tests
> Removes text from yearly report page

- components/profile/donations/DonationImpact/DonationImpact.tsx
- components/profile/donations/DonationImpact/DonationImpactItem.tsx
- components/profile/donations/DonationsAggregateImpactTable/DonationsAggregateImpactTable.tsx
- components/profile/shared/lists/Lists.module.scss
- components/profile/shared/lists/donationList/DonationDetails.module.scss
- components/profile/shared/lists/donationList/DonationDetails.tsx
- components/profile/shared/lists/donationList/DonationList.tsx
- pages/dashboard/DonationsPage.tsx
- studio/schemas/dashboard/donations.ts
- studio/schemas/schema.ts
- studio/schemas/siteSettings.ts
- studio/schemas/types/aggregateestimatedimpact.ts
- studio/schemas/types/donationstableconfiguration.ts
Adds frontend code for donations table in sanity and does some slight refactoring
- closes #739 
- closes #337 as a side effect of the window size listener
---
Tests
> Add donations table configuration to sanity

- _queries.ts
- pages/dashboard/AgreementsPage.tsx
- pages/dashboard/DonationsPage.tsx
> Remove type coercion

- package.json
- studio/resolveProductionUrl.ts
Shouldn't this work?
- closes #770 
---
Tests
Checkpoints
> Dynamic preview url

- components/main/blocks/Testemonial/Testemonial.module.scss
- components/main/blocks/Testemonial/Testemonial.tsx
- components/main/layout/PageHeader/PageHeader.module.scss
Quick fix for the arrows not working on mobile testemonials.
Also add a simple swipe gesture.
---
Tests
Checkpoints
> Testimonial arrow fix

- next.config.js
- package-lock.json
- package.json
- pages/_app.page.tsx
Adds a basic setup of Plausible just to test if it works in production.
We'll need to add an env variable in Vercel for the domain, but it looks like I don't have access to do it.
The proxy is added to the Next config for compatibility with adblockers. https://plausible.io/docs/proxy/introduction
> Adds Plausible Analytics provider

- components/profile/donations/DonationsStatus/DonationsStatus.Module.scss
- components/shared/components/Lightbox/Lightbox.module.scss
- components/shared/components/Lightbox/LightboxWithoutBotton.tsx
> feat: add new lightbox-component without cancel-button

- exampleDataStructure.json
> feat: add example json for donations timeline

- components/profile/donations/DonationsStatus/DonationStatusJson/DonationStatusJsonProps.tsx
- components/profile/donations/DonationsStatus/DonationStatusModal.tsx
- components/profile/shared/lists/donationList/DonationDetails.tsx
- components/profile/shared/lists/donationList/dummy.json
- components/shared/components/Timeline/DonationsTimeline.style.tsx
- components/shared/components/Timeline/DonationsTimeline.tsx
> feat: add functionality and jsonProps for timeline

- cypress/e2e/widget.js
Checking that logged in donor information is prefilled in the donation widget as expected
---
Tests
Checkpoints
> Add e2e existing donor donation test

- components/profile/tax/FacebookTaxWidget/FacebookTaxWidget.tsx
- components/shared/components/Widget/components/panes/DonorPane/DonorPane.tsx
- components/shared/components/Widget/components/panes/PaymentPane/Bank/ResultPane.tsx
- components/shared/components/Widget/config/anonymous-donor.ts
- components/shared/components/Widget/store/donation/actions.ts
- components/shared/components/Widget/store/donation/reducer.ts
- components/shared/components/Widget/store/donation/saga.ts
- components/shared/components/Widget/store/donation/types.ts
- components/shared/components/Widget/store/state.ts
- components/shared/components/Widget/types/Temp.ts
- package-lock.json
- package.json
Additional preparations for Swish
- closes #783 
---
Tests
Checkpoints
> Donor pane improvements

- components/profile/_queries.ts
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/DirectlyComplete.json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/DirectlyIncomplete.json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/bothComplete.json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/bothIncomplete .json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/bothWithDirctlyIncomplete.json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/bothWithSmartIncomplete.json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/dummy.json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/exportJsons.tsx
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/smartComplete.json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/smartIncomplete.json
- components/profile/shared/lists/donationList/DonationDetails.tsx
- package-lock.json
- package.json
> feat: add use of dummydata for every scenario

- components/profile/_queries.ts
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/bothComplete.json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/bothIncomplete .json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/bothWithDirctlyIncomplete.json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/bothWithSmartIncomplete.json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/nonComplete.json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/smartIncomplete.json
- components/shared/components/Timeline/DonationsTimeline.style.tsx
- components/shared/components/Timeline/DonationsTimeline.tsx
- components/shared/components/Timeline/TimelineFunctions.tsx
- components/shared/components/TimelinePreview/DonationsTimelinePreview.style.tsx
- components/shared/components/TimelinePreview/DonationsTimelinePreview.tsx
> feat: add correct timeline-margins in mobile version

- components/shared/components/Timeline/DonationsTimeline.style.tsx
- components/shared/components/Timeline/DonationsTimeline.tsx
- components/shared/components/Timeline/TimelineFunctions.tsx
> feat: grayed-out pending text

- components/profile/donations/DonationsStatus/DonationStatusModal.tsx
- components/profile/shared/lists/donationList/DonationDetails.tsx
- components/shared/components/FoldableDropDown/FoldableDropDown.module.scss
- components/shared/components/FoldableDropDown/FoldableDropDown.tsx
- components/shared/components/Lightbox/Lightbox.module.scss
- components/shared/components/Timeline/DonationsTimeline.tsx
- components/shared/components/Timeline/TimelineFunctions.tsx
- studio/schemas/types/donationstabledetailsconfiguration.ts
> feat: add Sanity configuration

- components/profile/donations/DonationsStatus/DonationStatusJson/DonationStatusJsonProps.tsx
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/bothComplete.json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/bothIncomplete .json
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/smartComplete.json
- components/profile/shared/lists/donationList/DonationDetails.tsx
- components/shared/components/Lightbox/Lightbox.module.scss
- components/shared/components/Timeline/DonationsTimeline.style.tsx
- components/shared/components/Timeline/DonationsTimeline.tsx
- components/shared/components/Timeline/TimelineFunctions.tsx
> fix: timeline codes use charityInfo from json-object

- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/bothIncomplete .json
- components/shared/components/Lightbox/Lightbox.module.scss
- components/shared/components/Timeline/DonationsTimeline.tsx
> feat: fix date and amount in the timeline

- components/profile/donations/DonationsStatus/DonationStatusJson/DonationStatusJsonProps.tsx
- components/profile/donations/DonationsStatus/DonationStatusJson/dummyJsons/bothComplete.json
- components/shared/components/Timeline/DonationsTimeline.tsx
- components/shared/components/Timeline/TimelineFunctions.tsx
- studio/schemas/types/donationstabledetailsconfiguration.ts
> feat: fix dates on donationstep

- components/shared/components/Widget/components/panes/DonorPane/DonorPane.style.tsx
- components/shared/components/Widget/components/panes/DonorPane/DonorPane.tsx
- components/shared/components/Widget/components/panes/Panes.style.tsx
- components/shared/components/Widget/components/panes/PaymentPane/PaymentPane.tsx
- components/shared/components/Widget/components/panes/PaymentPane/Swish/SwishPane.style.tsx
- components/shared/components/Widget/components/panes/PaymentPane/Swish/SwishPane.tsx
- components/shared/components/Widget/store/donation/actions.ts
- components/shared/components/Widget/store/donation/reducer.ts
- components/shared/components/Widget/store/donation/saga.ts
- components/shared/components/Widget/store/donation/types.ts
- components/shared/components/Widget/store/state.ts
- components/shared/components/Widget/types/WidgetProps.ts
- studio/schemas/types/paymentmethods/swish.ts
Add swish integration.
Requires stiftelsen-effekt/effekt-backend#600
- closes #712
---
Tests
Checkpoints
> Integrate swish

- components/shared/components/Widget/components/Widget.tsx
> Use single resize event listener

- components/main/blocks/BlockContentRenderer.tsx
- components/main/blocks/HTMLEmbed/HTMLEmbed.tsx
- components/main/blocks/SplitViewHtml/SplitViewHtml.module.scss
- components/main/blocks/SplitViewHtml/SplitViewHtml.tsx
- next.config.js
- studio/resolveProductionUrl.ts
- studio/schemas/schema.ts
- studio/schemas/types/contentsection.ts
- studio/schemas/types/splitviewhtml.ts
Adds a Split View block for HTML
- closes #828 
---
Tests
Checkpoints
> Adds html split view

- components/main/blocks/Links/Links.tsx
- package-lock.json
- package.json
- studio/resolveProductionUrl.ts
> Fix preview in preview

- components/main/blocks/BlockContentRenderer.tsx
- components/main/layout/SectionContainer/sectionContainer.tsx
- studio/components/contentSectionPreview.jsx
- studio/schemas/types/contentsection.ts
Adds a hidden toggle to content sections
- closes #821 
---
Tests
Checkpoints
> Adds a hidden toggle to content sections

- studio/deskStructure.ts
- studio/schemas/pages/article.ts
- studio/schemas/pages/articles.ts
- studio/schemas/pages/generic.ts
- studio/schemas/schema.ts
- studio/schemas/types/category.ts
Adds categories to sanity studio so that we can more easily organize the content
- closes #832
---
Tests
Checkpoints
> Adds categories for better structure in studio

- components/shared/layout/Footer/Footer.tsx
- studio/schemas/siteSettings.ts
Adds a configurable fourth footer column to sanity
- closes #824 
---
Tests
Checkpoints
> #824 fourth footer column

- components/main/layout/PageHeader/PageHeader.module.scss
- components/main/layout/PageHeader/PageHeader.tsx
- pages/GenericPage.tsx
- studio/schemas/types/pageheader.ts
For fundraisers
---
Tests
Checkpoints
> Adds a cover photo page header option

- components/shared/components/Widget/components/Widget.tsx
- components/shared/components/Widget/components/panes/DonorPane/DonorPane.tsx
- components/shared/components/Widget/types/WidgetProps.ts
- package-lock.json
- package.json
- closes #866 
---
Tests
Checkpoints
> Adds swedish ssn validation

- components/shared/components/Widget/components/Widget.tsx
- components/shared/components/Widget/components/panes/DonorPane/DonorPane.tsx
- components/shared/components/Widget/types/WidgetProps.ts
- studio/schemas/types/donationwidget.ts
Adds configurable privacy policy link
- closes #867 
---
Tests
Checkpoints
> #867 privacy policy link

- components/shared/components/Navbar/Navbar.module.scss
- components/shared/components/Navbar/Navbar.tsx
Fixes potential invert bug in profile page mobile menu
---
Tests
Checkpoints
> Attempt to use proper invertion

- components/shared/layout/CookieBanner/CookieBanner.tsx
- components/shared/layout/GoogleAnalytics.tsx
- components/shared/layout/GoogleTagManager.tsx
Uses implementation from next (https://github.com/vercel/next.js/blob/canary/packages/third-parties/src/google/gtm.tsx) _(package required next >13)_
---
Tests
Checkpoints
> Fix gtm integration

- components/main/blocks/OrganizationsList/OrganizationsList.module.scss
- components/main/blocks/OrganizationsList/OrganizationsList.tsx
- closes #924 
---
Tests
Checkpoints
> Adds separate styling to org subtitle

- components/shared/components/Widget/components/panes/PaymentPane/AutoGiro/AutogiroPane.tsx
- components/shared/components/Widget/components/panes/PaymentPane/AvtaleGiro/RecurringForm.tsx
- components/shared/components/Widget/components/panes/PaymentPane/Swish/SwishPane.tsx
- closes #933 
---
Tests
Checkpoints
> Add custom properties for swish and autogiro

- components/main/blocks/BlockContentRenderer.tsx
- components/main/blocks/DiscountRateComparison/DiscountRateComparison.module.scss
- components/main/blocks/DiscountRateComparison/DiscountRateComparison.tsx
- components/main/blocks/DiscountRateComparison/data.ts
- components/main/blocks/DiscountRateComparison/montecarlo.worker.ts
- components/main/blocks/DiscountRateComparison/util.ts
- components/shared/components/EffektSliderSdv/EffektSliderStdv.module.scss
- components/shared/components/EffektSliderSdv/EffektSliderStdv.tsx
- package-lock.json
- package.json
- studio/schemas/schema.ts
- studio/schemas/types/contentsection.ts
- studio/schemas/types/discountratecomparison.ts
Adds a little component im using for my articles on discount rates
---
Tests
Checkpoints
> Adds discount rate comparison block

- components/main/blocks/Accordion/Accordion.module.scss
- components/main/blocks/Accordion/Accordion.tsx
- components/main/blocks/BlockContentRenderer.tsx
- components/main/blocks/Paragraph/Citation.tsx
- studio/components/katexInput.jsx
- studio/components/katexPreview.jsx
- studio/package-lock.json
- studio/package.json
- studio/schemas/schema.ts
- studio/schemas/types/accordion.ts
- studio/schemas/types/blockcontent.ts
- studio/schemas/types/contentsection.ts
- studio/schemas/types/latex.ts
Adds components needed for discount rates article
---
Tests
Checkpoints
> Adds latex rendering and an accordion component

- _queries.ts
- components/main/blocks/BlockContentRenderer.tsx
- components/main/blocks/Contributors/Contributor.module.scss
- components/main/blocks/Contributors/Contributor.tsx
- components/main/blocks/Links/Links.tsx
- components/main/blocks/PhilantropicTeaser/PhilantropicTeaser.module.scss
- components/main/blocks/PhilantropicTeaser/PhilantropicTeaser.tsx
- studio/schemas/schema.ts
- studio/schemas/types/contentsection.ts
- studio/schemas/types/philantropicteaser.ts
Adds a teaser for the philantropic page
- closes #766 
---
Tests
Checkpoints
> Adds philantropic teaser

- components/main/blocks/WealthCalculator/_queries.ts
- pages/api/tax.page.ts
Sets up our own proxy in vercel to handle Cors issues
- closes #975 
---
Tests
Checkpoints
> Use our own proxy for tax calculations

- components/shared/components/Widget/components/Widget.tsx
Look at the URL and look for a query param
that specifies a payment distribution to prefill
If found, set the distribution cause areas and organizations
to the prefilled values.
Find the corresponding cause area and organization in the state
Use next router to look at the query params
The format of the query param is:
distribution=causeAreaId:share:organizationId-share:organizationId-share
E.g.
1:100:4-50:1-25:12-25
This would set cause area 1 to 100% and distribute the shares
between organizations 4, 1 and 12 with 50%, 25% and 25% respectively
- closes #979 
---
Tests
Checkpoints
> Adds query params format to prefill widget

- components/main/blocks/Teasers/Teasers.module.scss
- components/main/blocks/Teasers/Teasers.tsx
- components/main/blocks/TeasersItem/TeasersItem.module.scss
- components/main/blocks/TeasersItem/TeasersItem.tsx
- components/shared/responsiveimage.tsx
- studio/sanity.config.ts
Updates the teaser component to use updated teaser design
---
Tests
Checkpoints
> Updates teaser items to the new design

- components/main/blocks/BlockContentRenderer.tsx
- components/main/blocks/ResultsTeaser/ResultsTeaser.module.scss
- components/main/blocks/ResultsTeaser/ResultsTeaser.tsx
- components/shared/components/Graphs/Area/AreaGraph.tsx
- cypress/e2e/no/agreements.js
- cypress/e2e/no/donations.js
- cypress/e2e/no/navigation.js
- cypress/e2e/no/organizations.js
- cypress/e2e/no/wealthcalculator.js
- cypress/e2e/no/widget.js
- cypress/e2e/no/yearly-reports-crypto-donations.js
- cypress/e2e/no/yearly-reports-ea-funds-donations.js
- cypress/e2e/no/yearly-reports-missing-ssn.js
- cypress/e2e/no/yearly-reports-no-data.js
- cypress/e2e/no/yearly-reports-valid.js
- cypress/e2e/se/widget.js
- studio/schemas/schema.ts
- studio/schemas/types/contentsection.ts
- studio/schemas/types/resultsteaser.ts
Adds a results teaser for use on the front page
---
Tests
Checkpoints
> Adds a results teaser

- components/main/blocks/InterventionWidget/InterventionWidgetOutput.tsx
Uses current date for currency conversion in intervention widget
---
Tests
Checkpoints
> Use current date for conversions for impact estimates

- _queries.ts
- components/main/blocks/BlockContentRenderer.tsx
- components/main/blocks/DKMembershipDisplay/DKMemberShipDisplay.tsx
- components/main/blocks/MediaCoverageTeaser/MediaCoverageTeaser.module.scss
- components/main/blocks/MediaCoverageTeaser/MediaCoverageTeaser.tsx
- components/main/blocks/ResultsTeaser/ResultsTeaser.tsx
- components/main/blocks/TaxDeductionWidget/TaxDeductionBarChart.tsx
- components/main/blocks/TaxDeductionWidget/TaxDeductionWidget.tsx
- components/shared/components/EffektButton/EffektButton.module.scss
- components/shared/components/Widget/components/Widget.tsx
- lib/sanity.client.ts
- studio/sanity.types.ts
- studio/schema.json
- studio/schemas/schema.ts
- studio/schemas/types/contentsection.ts
- studio/schemas/types/mediacoverageteaser.ts
- studio/schemas/types/resultsteaser.ts
- studio/schemas/types/taxdeductionwidget.ts
Fixes a bunch of smaller translation issues for DK components
---
Tests
Checkpoints
> Smaller dk component updates

- components/shared/components/Widget/components/Widget.tsx
- components/shared/components/Widget/components/panes/DonorPane/DonorPane.tsx
- components/shared/components/Widget/config/methods.ts
- components/shared/components/Widget/types/Enums.ts
- components/shared/components/Widget/types/WidgetProps.ts
- studio/deskStructure.ts
- studio/schemas/schema.ts
- studio/schemas/types/donationwidget.ts
- studio/schemas/types/paymentmethods/quickpaycard.ts
- studio/schemas/types/paymentmethods/quickpaymobilepay.ts
Differentiates between quickpay card and mobilepay
---
Tests
Checkpoints
> Differentiate between quickpay card and quickpay mobilepay

- components/shared/components/Navbar/Navbar.tsx
- context/RouterContext.ts
- lib/sanity.client.ts
- next.config.ts
Adds caching to the CI when building the entire page, reducing the API CDN requests to Sanity by several thousands per build.
---
Tests
Checkpoints
> Adds a caching setup to reduce API cdn requests

- _queries.ts
- components/main/blocks/BlockContentRenderer.tsx
- components/main/blocks/Contributors/Contributor.tsx
- components/main/blocks/PhilantropicTeaser/PhilantropicTeaser.tsx
- components/main/blocks/WealthCalculator/WealthCalculator.tsx
- components/main/blocks/WealthCalculator/WealthCalculatorImpact.tsx
- components/main/blocks/WealthCalculator/_queries.ts
- pages/ResultsPage.tsx
- studio/deskStructure.ts
- studio/package-lock.json
- studio/package.json
- studio/sanity.types.ts
- studio/schema.json
- studio/schemas/schema.ts
- studio/schemas/types/contributor.ts
- studio/schemas/types/interventionwidgetoutputconfiguration.ts
- studio/schemas/types/wealthcalculator.ts
- studio/schemas/types/wealthcalculatorimpact.ts
Small DK updates
---
Tests
Checkpoints
> Philantropic advisor dk

- components/shared/components/Widget/components/Widget.tsx
- components/shared/components/Widget/components/shared/ApiErrorNotification/ApiErrorNotification.style.tsx
- components/shared/components/Widget/components/shared/ApiErrorNotification/ApiErrorNotification.tsx
- components/shared/components/Widget/store/donation/actions.ts
- components/shared/components/Widget/store/donation/reducer.ts
- components/shared/components/Widget/store/donation/saga.ts
- components/shared/components/Widget/store/donation/types.ts
- components/shared/components/Widget/store/state.ts
- components/shared/components/Widget/types/WidgetProps.ts
- studio/schemas/types/donationwidget.ts
Adds an error messsage field when the API returns errors
---
Tests
Checkpoints
> Adds API error message

- components/main/blocks/Links/Links.tsx
- components/main/blocks/PhilantropicTeaser/PhilantropicTeaser.tsx
- components/main/blocks/WealthCalculatorTeaser/WealthCalculatorTeaser.tsx
Support links to fundraisers for navitems
---
Tests
Checkpoints
> Support links to fundraisers for navitems

- components/shared/seo/Seo.tsx
- models.ts
- pages/ArticlePage.tsx
- pages/GenericPage.tsx
- pages/ResultsPage.tsx
- pages/VippsAgreementPage.tsx
- pages/sitemap.xml.page.tsx
- studio/sanity.types.ts
- studio/schema.json
- studio/schemas/types/articleheader.ts
- studio/schemas/types/pageheader.ts
Let's users specify that a page should not be indexed by search engines.
---
Tests
Checkpoints
> Adds the option to explicitly not index pages for SEO
